### ISSUE TITLE
Если ты хочешь таким образом сделать эту стрелочку, то лучше сделать обертку, и именно ссылку внутри развернуть, а то сейчас получается, что разворачивается весь блок (см.картинку)

### ISSUE THREAD

**Issue by igosheva** [Minor353/-LS-MrBurger#4]
![2018-01-24 11-56-57](https://user-images.githubusercontent.com/22238895/35323264-fc0f98b4-00fd-11e8-8f7e-e5a2e6f17475.png)
https://github.com/Minor353/-LS-MrBurger/blob/7812958e1fe4df4f7210cee3843fd96a7879b13d/work/index.html#L42

**Comment by igosheva** [comment]
Плюс стрелочка под этой стелкой не ровно под ней появляется

**Comment by igosheva** [comment]
И тогда она тоже должна быть кликабельной и вести в о вторую секцию

**Comment by Minor353** [comment]
Исправлено
