### ISSUE TITLE
Контент не по центру (вертикаль) http://joxi.ru/eAONKd5U48yaw2

### ISSUE THREAD

**Issue by igosheva** [Minor353/-LS-MrBurger#5]
https://github.com/Minor353/-LS-MrBurger/blob/7812958e1fe4df4f7210cee3843fd96a7879b13d/work/index.html#L92

**Comment by igosheva** [comment]
Плюс контент этой секции тоже должен быть обернут контейнером)

**Comment by Minor353** [comment]
Исправлено
