### ISSUE TITLE
Не забудь к скрытому элементу добавить паддинги чтобы текст не плипал к границам блока http://joxi.ru/ZrJ05MEi1xJZp2

### ISSUE THREAD

**Issue by igosheva** [Minor353/-LS-MrBurger#8]
https://github.com/Minor353/-LS-MrBurger/blob/7812958e1fe4df4f7210cee3843fd96a7879b13d/work/index.html#L176

**Comment by Minor353** [comment]
Падинги добавляются в состоянии active
